#! /bin/sh

# OVH - DynHost
#
# Permet de mettre à jour le champ DYNHOST
# pour votre nom de domaine.
# Utilise l'adresse de l'interface ppp0 de 
# votre système Linux.

# La mise à jour ne se fait que si l'adresse IP
# a effectivement changé.
# Fichier de log: dynhost.log

IFACE=wwan0
HOST=host.alu-streamz.mobi
LOGIN=alu-streamz.mobi-user
PASSWORD=pass
OPTIONS=""

BASEDIR=$(dirname $0)
cd $BASEDIR

getip() {
		OLDIP=`cat ./old.ip`
		IP=`/sbin/ifconfig $IFACE | grep -e 'inet6.*Global' | tr -s " " | cut -d" " -f4 | cut -d"/" -f1`
		if [ -z "$IP" ]; then
			IP=`/sbin/ifconfig $IFACE | fgrep "inet ad" | cut -f2 -d":" | cut -f1 -d" "`
		fi
		}
#

	echo ---------------------------------- >> ./dynhost.log
	echo `date` >> ./dynhost.log 
	echo Démarrage de DynHost >> ./dynhost.log
	getip

	if [ "$IP" ]; then
		if [ "$OLDIP" != "$IP" ]; then
			echo -n "Ancienne IP: " >> ./dynhost.log
                	echo $OLDIP >> ./dynhost.log
               		echo -n "Nouvelle IP: " >> ./dynhost.log
              		echo $IP >> ./dynhost.log
			echo "Mise à jour!" >> ./dynhost.log
			if [ "$OPTIONS" =  "" ]; then 
				OPTIONS="-a $IP" 
			fi
			
			python ipcheck.py $OPTIONS $LOGIN $PASSWORD $HOST >> ./dynhost.log
			echo -n "$IP" > ./old.ip				
         	else
               		echo IP Identique! Pas de mise à jour. >> ./dynhost.log
         	fi
         else
	 	echo Panique à bord: Aucune IP Disponible!! >> ./dynhost.log
         fi

